### ISSUE TITLE
Using wrong python under Arch Linux

### ISSUE THREAD

**Issue by despairblue** [atom/node-oniguruma#18]
The package should link against `python2` on ArchLinux.

Using `npm install oniguruma --python=/usr/bin/python2` works, but the python switch seems to be ignored by apm since `apm install atom-color-highlight --python=/usr/bin/python2` will fail. 

Not sure whether this should be fixed here or in apm.
```
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:106:14)
gyp ERR! stack     at /usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/lib/configure.js:95:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:635:7)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:743:16)
gyp ERR! stack     at Socket.<anonymous> (child_process.js:956:11)
gyp ERR! stack     at Socket.EventEmitter.emit (events.js:95:17)
gyp ERR! stack     at Pipe.close (net.js:465:12)
gyp ERR! System Linux 3.14.6-1-ARCH
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-114624-25771-1w155hl/node_modules/atom-color-highlight/node_modules/oniguruma
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/debug
npm http 200 https://registry.npmjs.org/color
npm ERR! oniguruma@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@2.0.0 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/css-color-function
npm http GET https://registry.npmjs.org/rgb/0.0.1
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/color
npm http GET https://registry.npmjs.org/balanced-match/0.0.0
npm ERR! oniguruma@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@2.0.0 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.14.6-1-ARCH
npm ERR! command "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/bin/node" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/home/despairblue/.atom/.apmrc" "install" "/home/despairblue/.atom/.node-gyp/.atom/.apm/atom-color-highlight/0.19.2/package.tgz" "--target=0.11.10" "--arch=x64"
npm ERR! cwd /tmp/apm-install-dir-114624-27615-1yxkm3u
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.4
npm ERR! code ELIFECYCLE
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/color
npm http 304 https://registry.npmjs.org/balanced-match/0.0.0
npm http 304 https://registry.npmjs.org/rgb/0.0.1
npm http GET https://registry.npmjs.org/color-convert
npm http GET https://registry.npmjs.org/color-string
npm http 304 https://registry.npmjs.org/color-convert
npm http 304 https://registry.npmjs.org/color-string
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /tmp/apm-install-dir-114624-27615-1yxkm3u/npm-debug.log
npm ERR! not ok code 0
```

**Comment by 5shekel** [comment]
thanks for the 
`npm config set python /usr/bin/python2 -g`

this solution it stills valid

**Comment by zcbenz** [comment]
All native node modules have this issue, a better place to report this is node-gyp's repo, there is basically no way for us to fix it on our side.
