### ISSUE TITLE
Fail when installing from NPM 

### ISSUE THREAD

**Issue by tian2992** [atom/node-oniguruma#44]
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/node-gyp/lib/configure.js:352:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.7-24-desktop
gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/oniguruma
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.7-24-desktop
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "oniguruma"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

**Comment by davideghz** [comment]
let's try apt-get remove gyp
and npm install again
reference:
https://github.com/nodejs/node-gyp/issues/363#issuecomment-32234646
