### ISSUE TITLE
node-gyp rebuild fails for vscode build on Windows 10

### ISSUE THREAD

**Issue by adyavanapalli** [atom/node-oniguruma#61]
Stack trace:
```
40457 verbose stack Error: oniguruma@6.1.1 install: `node-gyp rebuild`
40457 verbose stack Exit status 1
40457 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
40457 verbose stack     at emitTwo (events.js:106:13)
40457 verbose stack     at EventEmitter.emit (events.js:194:7)
40457 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
40457 verbose stack     at emitTwo (events.js:106:13)
40457 verbose stack     at ChildProcess.emit (events.js:194:7)
40457 verbose stack     at maybeClose (internal/child_process.js:899:16)
40457 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
40458 verbose pkgid oniguruma@6.1.1
```
Full log file below:
[npm-debug.log.txt](https://github.com/atom/node-oniguruma/files/829034/npm-debug.log.txt)

**Comment by jrmiller82** [comment]
Same here.

**Comment by oliversalzburg** [comment]
Make sure you have the correct Visual Studio version declared in your npm config. If you're using VS Community 2017, you should declare it like this:

```
npm config set msvs_version 2017
```
