### ISSUE TITLE
node-gyp rebuild failing on Windows 7 x64 with VS2008 express

### ISSUE THREAD

**Issue by ameyp** [atom/node-oniguruma#9]
```
C:\Users\ameyp\tmp>npm cache clear

C:\Users\ameyp\tmp>npm install oniguruma
npm http GET https://registry.npmjs.org/oniguruma
npm http 200 https://registry.npmjs.org/oniguruma
npm http GET https://registry.npmjs.org/oniguruma/-/oniguruma-2.0.0.tgz
npm http 200 https://registry.npmjs.org/oniguruma/-/oniguruma-2.0.0.tgz
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/bindings
npm http 200 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz
npm http 200 https://registry.npmjs.org/bindings/-/bindings-1.0.0.tgz
npm http 200 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/nan/-/nan-0.8.0.tgz
npm http 200 https://registry.npmjs.org/nan/-/nan-0.8.0.tgz

> oniguruma@2.0.0 install C:\Users\ameyp\tmp\node_modules\oniguruma
> node-gyp rebuild


C:\Users\ameyp\tmp\node_modules\oniguruma>node "C:\Users\ameyp\Apps\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
VCBUILD : error : project file 'C:\Users\ameyp\tmp\node_modules\oniguruma\build\oniguruma.vcproj' was not found or not a valid project file.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v3.5\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\ameyp\Apps\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Users\\ameyp\\Apps\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ameyp\tmp\node_modules\oniguruma
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm ERR! oniguruma@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the oniguruma@2.0.0 install script.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Users\\ameyp\\Apps\\nodejs\\\\node.exe" "C:\\Users\\ameyp\\Apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "oniguruma"
npm ERR! cwd C:\Users\ameyp\tmp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\ameyp\tmp\npm-debug.log
npm ERR! not ok code 0

C:\Users\ameyp\tmp>
```

**Comment by FlavorScape** [comment]
same. errors all abound with installing

**Comment by flyfishMT** [comment]
Windows 10, VS 2015 - 

<mypath>\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [<mypath>\node_modu
les\highlights\node_modules\first-mate\node_modules\oniguruma\build\oniguruma.v
cxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd <mypath>\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

**Comment by FlavorScape** [comment]
this is an old old version of node. i was having issue like this and gave in and upgraded all my deps. using node 4.x now

**Comment by flyfishMT** [comment]
I updated to 4.3.3 and npm 3.4.1 and still get it - 
> TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [<path>\\node_m
odules\oniguruma\build\oniguruma.vcxproj]
...
> npm ERR! node v4.2.2
> npm ERR! npm  v3.4.1

**Comment by Barryrowe** [comment]
FYI,

This occurs for me on as well with Node 5.0.0 and npm 3.4.1 on Windows 7 

Both VS2013 and VS2015 are installed and MSBuild v14.0 is being picked up (see error below)

I'm attempting to run npm install for the VSCode project detailed here: (https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source)

Full error:

    TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [H:\git-repos\vscode\node_modules\vscode-textmate\nod
    e_modules\oniguruma\build\oniguruma.vcxproj]


    gyp ERR! build error
    gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onExit (C:\Users\E027694\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Windows_NT 6.1.7601
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E027694\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd H:\git-repos\vscode\node_modules\vscode-textmate\node_modules\oniguruma
    gyp ERR! node -v v5.0.0
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
    Code@0.10.3 H:\git-repos\vscode
    └── sax@1.1.2

    npm ERR! Windows_NT 6.1.7601
    npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\E027694\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
    npm ERR! node v5.0.0
    npm ERR! npm  v3.4.1
    npm ERR! code ELIFECYCLE
    
    npm ERR! oniguruma@5.1.1 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the oniguruma@5.1.1 install script 'node-gyp rebuild'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the oniguruma package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls oniguruma
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     H:\git-repos\vscode\npm-debug.log

**Comment by shawumu** [comment]
@Barryrowe .I  encounter the same problem when I was build the VSCode
